### ISSUE TITLE
What can this hacked client do?

### ISSUE THREAD

**Issue by blacbrue** [Jack06WS/kahoot#1]
title says all

**Comment by Jack06WS** [comment]
Hi there! There is an invisible button at the bottom right of the website, pressing this brings up the modding menu. Also, once entering your Game Pin and Username, you can type in the name of the quiz that you are completing and a rainbow line will appear around the correct answers.

**Comment by blacbrue** [comment]
Okay thank you

**Comment by demonkrafin** [comment]
cant find the button
